export const COMMON_SET_TITLE = `COMMON_SET_TITLE`;
export const COMMON_SET_FULLSCREEN = `COMMON_SET_FULLSCREEN`;

export const AUTH_SET_DATA = `AUTH_SET_DATA`;

export const CONSOLE_SET_LOADING = `CONSOLE_SET_LOADING`;
export const CONSOLE_SET_HISTORY = `CONSOLE_SET_HISTORY`;
export const CONSOLE_SET_REQUEST = `CONSOLE_SET_REQUEST`;
export const CONSOLE_SET_RESPONSE = `CONSOLE_SET_RESPONSE`;
export const CONSOLE_SET_RESPONSE_ERROR = `CONSOLE_SET_RESPONSE_ERROR`;
export const CONSOLE_SET_REQUEST_ERROR = `CONSOLE_SET_REQUEST_ERROR`;
